### ISSUE TITLE
1.20.1 crashes with no other mods doesn't load

### ISSUE THREAD

**Issue by thiccmeme** [Potion-Studios/Oh-The-Biomes-Weve-Gone#10]
running java 21 

forge 1.20.1 3.5 

  [✔] corgilib-forge-1.20.1-4.0.2.0
  [✔] geckolib-forge-1.20.1-4.4.7
  [✔] Oh The Trees You'll Grow-forge-1.20.1-1.2.0
  [✔] Oh-The-Biomes-Weve-Gone-Forge-1.0.1-Beta
  [✔] TerraBlender-forge-1.20.1-3.0.1.7

only above mods installed on prism mc

all I get in the error log is:

Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.module.ResolutionException: Module jankson reads more than one module named com.electronwill.nightconfig.toml
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:721)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 5 more
Exiting with ERROR
Process exited with code 2.

**Comment by Eletoast** [comment]
Seems to be a config issue. I'm assuming this mod will help that out: [(https://www.curseforge.com/minecraft/mc-mods/night-config-fixes/files/4614068)].

**Comment by thiccmeme** [comment]
the issue seems to be CorgiLib as on it's git issues there are posts of a crash with the same output.

unfortunately seems to be an issue with only the latest version and downgrading would fix in any situation other than this as the latest version is required for BWG to load :/

hopfully this nightconfig mod can fix the issue for now

**Comment by CorgiTaco** [comment]
Use the one on curseforge. The one on modrinth refuses to delete hence why it hasn't been fixed.

**Comment by RoomAlex68** [comment]
The game still crashes with the new BWG version 1.0.1 stating Corgilib is causing the crash

**Comment by CorgiTaco** [comment]
@RoomAlex68 send your crash report

**Comment by RoomAlex68** [comment]
> @RoomAlex68 send your crash report

Sorry for a late response but he is the crash log:
![crash-2024-07-29_13.31.29-client.txt](https://github.com/user-attachments/files/16419667/crash-2024-07-29_13.31.29-client.txt)
