### ISSUE TITLE
[Bug] Compatibility WWEE + BWG

### ISSUE THREAD

**Issue by SylisMC** [Potion-Studios/Oh-The-Biomes-Weve-Gone#128]
Game crashes (Locks up) on generating a world

MC: 1.21.1
Fabric API [0.105.0+1.21.1]
Oh The Biomes We've Gone [2.1.0-Beta]
TerraBlender [4.1.0.3]
CorgiLib [5.0.0.2]
Oh The Trees You'll Grow [5.0.3]
GeckoLib 4 [4.6.5]
Cristel Lib [1.2.8]
Expanded Ecosphere [3.4.2]

WWEE Report: https://github.com/Cristelknight999/Expanded-Ecosphere/issues/114
BWG Report: https://github.com/Potion-Studios/Oh-The-Biomes-Weve-Gone/issues/128

Thanks :)

`[12:29:55] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.class_3898.method_60445(class_3898.java:647) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:552) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:561) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18857(class_3215.java:525) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_12121(class_3215.java:137) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8402(class_1937.java:208) ~[client-intermediary.jar:?]
	at net.minecraft.class_4538.method_22342(class_4538.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8497(class_1937.java:202) ~[client-intermediary.jar:?]
	at net.minecraft.class_5322.method_29194(class_5322.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_5322.method_29196(class_5322.java:64) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_27901(MinecraftServer.java:453) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:386) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:342) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3823(class_1132.java:73) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:664) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / wythers:autumnal_forest_edge]=net.minecraft.class_1959@17d05d19}, Reference{ResourceKey[minecraft:worldgen/biome / biomeswevegone:temperate_grove]=net.minecraft.class_1959@10f3ecc}, Reference{ResourceKey[minecraft:worldgen/biome / biomeswevegone:mojave_desert]=net.minecraft.class_1959@6501ee2c}, Reference{ResourceKey[minecraft:worldgen/biome / biomeswevegone:firecracker_chaparral]=net.minecraft.class_1959@3a523b6d}]
	at net.minecraft.class_7510.method_44210(class_7510.java:99) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.impl.biome.modification.BiomeModificationImpl.lambda$finalizeWorldGen$5(BiomeModificationImpl.java:164) ~[fabric-biome-api-v1-13.0.29+5bd9f1bc19-4cf0d8b009ee3a5a.jar:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181) ~[guava-32.1.2-jre.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:292) ~[client-intermediary.jar:?]
	at net.minecraft.class_9310.method_57610(class_9310.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_9770.method_60560(class_9770.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_60442(class_3898.java:632) ~[client-intermediary.jar:?]
	at net.minecraft.class_9761.method_60461(class_9761.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_9759.method_60428(class_9759.java:143) ~[client-intermediary.jar:?]
	at net.minecraft.class_9759.method_60427(class_9759.java:121) ~[client-intermediary.jar:?]
	at net.minecraft.class_9759.method_60432(class_9759.java:74) ~[client-intermediary.jar:?]
	at net.minecraft.class_9759.method_60424(class_9759.java:59) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_60446(class_3898.java:665) ~[client-intermediary.jar:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Process was killed by user.`

**Comment by SylisMC** [comment]
[Cristelknight999](https://github.com/Cristelknight999) ~ "Currently working on this: https://github.com/Cristelknight999/Expanded-Ecosphere/issues/107"
