### ISSUE TITLE
Black Screen in Minecraft World [Feature Cycle]

### ISSUE THREAD

**Issue by DavidFlisar** [Potion-Studios/Oh-The-Biomes-Weve-Gone#141]
Hi. Just wanted to let you know that I added your mod in my testing mod pack that I later push out, but I encountered a weird issue. The whole screen turns black. I had to kill the task by hand and look at the issue. 
Upon further investigation by myself and also having ChatGPT specifically trained to spot issues within my code it concluded it had something to do with the interference with 4 of my mods, including yours. 

Here is the error I got: "
[16:00:41] [Render thread/WARN]: Time from main menu to in-game was 20.085104 seconds
[16:00:41] [Render thread/WARN]: Total time to load game and open world was 81.9101 seconds
[16:00:41] [Thread-76/INFO]: [EMI] Reloaded plugin from emi in 1850ms
[16:00:41] [Thread-76/INFO]: [EMI] Clearing data
[16:00:42] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
net.minecraft.ReportedException: Exception generating new chunk
	at net.minecraft.server.level.ChunkMap.m_214912_(ChunkMap.java:658) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:541) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:549) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:269) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:758) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:581) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.client.server.IntegratedServer.m_7041_(IntegratedServer.java:187) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / organics:hoaky_forest]=net.minecraft.world.level.biome.Biome@2390bd80}, Reference{ResourceKey[minecraft:worldgen/biome / biomeswevegone:ebony_woods]=net.minecraft.world.level.biome.Biome@66ab188f}, Reference{ResourceKey[minecraft:worldgen/biome / biomeswevegone:jacaranda_jungle]=net.minecraft.world.level.biome.Biome@77b2c7a4}, Reference{ResourceKey[minecraft:worldgen/biome / alexscaves:abyssal_chasm]=net.minecraft.world.level.biome.Biome@8f57e92}]
	at net.minecraft.world.level.biome.FeatureSorter.m_220603_(FeatureSorter.java:100) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.mcreator.organics.init.OrganicsModBiomes.lambda$onServerAboutToStart$1(OrganicsModBiomes.java:64) ~[Organics-1.20.1-0.1.9.jar%23604!/:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar%23109!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:288) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_279978_(ChunkStatus.java:108) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:309) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%23114!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
"

ChatGPT returned me these instructions aswell: "

From the error log, it appears that there is a circular dependency or conflict in biome generation between several mods:

    organics:hoaky_forest
    biomeswevegone:ebony_woods
    biomeswevegone:jacaranda_jungle
    alexscaves:abyssal_chasm

The key part of the error is:
java.lang.IllegalStateException: Feature order cycle found, involved sources: [...]

This indicates that the game encountered a problem where biomes or their features are depending on each other in a way that creates a loop, causing the chunk generation to fail.
"

I know it may not be your mod, but it was the last of the 3 other mods I had from the beginning of my modpack, which is like a few good months and no mod of these 3 had a recent update as far as I know, which may lead to your mod causing it to turn black screen.

I hope you find a way to fix this perhaps, so I can include your awesome mod in my modpack :)

**Comment by CorgiTaco** [comment]
For now use: https://legacy.curseforge.com/minecraft/mc-mods/feature-recycler/files until a more official fix is done

**Comment by JT122406** [comment]
@DavidFlisar What BWG version?

**Comment by JT122406** [comment]
#164 Is the same as this follow along there
