### ISSUE TITLE
crash mod on server

### ISSUE THREAD

**Issue by MehanikTMYT** [Potion-Studios/Oh-The-Biomes-Weve-Gone#190]
-- Mod loading issue for: biomeswevegone --
Details:
	Mod file: /content/gdrive/MyDrive/server/mods/Oh-The-Biomes-Weve-Gone-NeoForge-2.2.5.jar
	Failure message: Oh The Biomes We've Gone (biomeswevegone) encountered an error while dispatching the net.neoforged.neoforge.registries.RegisterEvent event
		java.lang.NullPointerException: Trying to access unbound value: ResourceKey[minecraft:item / biomeswevegone:white_puffball_spores]
	Mod version: 2.2.5
	Mod issues URL: https://github.com/Potion-Studios/Oh-The-Biomes-Weve-Gone/issues
	Exception message: java.lang.NullPointerException: Trying to access unbound value: ResourceKey[minecraft:item / biomeswevegone:white_puffball_spores]
Stacktrace:
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredHolder.value(DeferredHolder.java:103) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredHolder.get(DeferredHolder.java:117) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/biomeswevegone@2.2.5/net.potionstudios.biomeswevegone.world.entity.npc.BWGVillagerProfessions.lambda$static$0(BWGVillagerProfessions.java:22) ~[Oh-The-Biomes-Weve-Gone-NeoForge-2.2.5.jar%23418!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:215) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.lambda$register$1(DeferredRegister.java:234) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.lambda$addEntries$2(DeferredRegister.java:375) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.RegisterEvent.register(RegisterEvent.java:48) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.addEntries(DeferredRegister.java:375) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26) ~[bus-8.0.2.jar%2367!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%2367!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:329) ~[bus-8.0.2.jar%2367!/:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:177) ~[loader-4.0.34.jar%2360!/:4.0] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.lambda$postEventWithWrapInModOrder$16(ModLoader.java:379) ~[loader-4.0.34.jar%2360!/:4.0] {}
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModList.forEachModInOrder(ModList.java:174) ~[loader-4.0.34.jar%2360!/:4.0] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:377) ~[loader-4.0.34.jar%2360!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.postEventWrapContainerInModOrder(ModLoader.java:368) ~[loader-4.0.34.jar%2360!/:4.0] {}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.GameData.postRegisterEvents(GameData.java:92) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.internal.CommonModLoader.lambda$begin$0(CommonModLoader.java:54) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] {}
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] {}
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}

**Comment by JT122406** [comment]
Try on 2.3.0

**Comment by JT122406** [comment]
Any update here?

**Comment by MehanikTMYT** [comment]
sorry for long answer, yes it was work with 2.3.0

**Comment by xAlicatt** [comment]
So is this not going to be fixed on older versions? Trying to boot up a 1.20.1 Forge server and running into this issue

**Comment by JT122406** [comment]
Are you using the latest bwg for 1.20.1? as the change in 2.3.0 is in the versions for 1.20.1

**Comment by xAlicatt** [comment]
Running 1.5.5

**Comment by JT122406** [comment]
Also you need to send your error since it can't be this exact one as this one is a neoforge based error
