### ISSUE TITLE
crash when clicking fruits on server

### ISSUE THREAD

**Issue by Weylend** [Potion-Studios/Oh-The-Biomes-Weve-Gone#4]
```
java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "this.fruit" is null
	at net.potionstudios.biomeswevegone.world.level.block.plants.tree.fruit.BWGFruitBlock.method_9534(BWGFruitBlock.java:80)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133)
	at net.minecraft.class_636.method_41934(class_636.java:347)
	at net.minecraft.class_636.method_41933(class_636.java:324)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:323)
	at net.minecraft.class_310.method_1583(class_310.java:1802)
	at net.minecraft.class_310.method_1508(class_310.java:2060)
	at net.minecraft.class_310.method_1574(class_310.java:1883)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
```

**Comment by JT122406** [comment]
> ```
> java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "this.fruit" is null
> 	at net.potionstudios.biomeswevegone.world.level.block.plants.tree.fruit.BWGFruitBlock.method_9534(BWGFruitBlock.java:80)
> 	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133)
> 	at net.minecraft.class_636.method_41934(class_636.java:347)
> 	at net.minecraft.class_636.method_41933(class_636.java:324)
> 	at net.minecraft.class_636.method_41931(class_636.java:278)
> 	at net.minecraft.class_636.method_2896(class_636.java:323)
> 	at net.minecraft.class_310.method_1583(class_310.java:1802)
> 	at net.minecraft.class_310.method_1508(class_310.java:2060)
> 	at net.minecraft.class_310.method_1574(class_310.java:1883)
> 	at net.minecraft.class_310.method_1523(class_310.java:1181)
> 	at net.minecraft.class_310.method_1514(class_310.java:802)
> 	at net.minecraft.client.main.Main.main(Main.java:250)
> ```

Any fruit?
Also can you send what server software and version

**Comment by JT122406** [comment]
Also what type of click like a break or like a bone meal or?

**Comment by JT122406** [comment]
Going to be pushing a patch for this in the next few hours
