### ISSUE TITLE
Crash - Sakura Grove

### ISSUE THREAD

**Issue by lanwoodall423** [Potion-Studios/Oh-The-Biomes-Weve-Gone#55]
Fabric 1.20.1 with OTBWG 1.0.3 Beta

Crash while exploring new chunks. I don't think I have any of the recently reported mods like Nature's Spirit or Abnormals. 

[crash-2024-08-02_13.12.34-server.txt](https://github.com/user-attachments/files/16473347/crash-2024-08-02_13.12.34-server.txt)
[latest.log](https://github.com/user-attachments/files/16473356/latest.log)

Description: Exception ticking world

java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / wythers:sakura_forest]=net.minecraft.world.biome.Biome@2b2faf61}, Reference{ResourceKey[minecraft:worldgen/biome / biomeswevegone:sakura_grove]=net.minecraft.world.biome.Biome@31a1fd89}]
	at MC//net.minecraft.world.gen.feature.util.PlacedFeatureIndexer.collectIndexedFeatures(PlacedFeatureIndexer.java:100)
	at MC//net.minecraft.world.gen.chunk.ChunkGenerator.method_44215(ChunkGenerator.java:102)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at MC//net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator.java:288)
	at MC//net.minecraft.world.chunk.ChunkStatus.method_51375(ChunkStatus.java:108)
	at MC//net.minecraft.world.chunk.ChunkStatus$SimpleGenerationTask.doWork(ChunkStatus.java:309)
	at MC//net.minecraft.world.chunk.ChunkStatus.md85bdfa$c2me-threading-worldgen$lambda$runGenerationTask$0$5(ChunkStatus.java:2608)
	at java.base@21.0.1/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base@21.0.1/java.lang.Thread.run(Thread.java:1583)

**Comment by lanwoodall423** [comment]
[crash-2024-08-02_14.16.46-server.txt](https://github.com/user-attachments/files/16473895/crash-2024-08-02_14.16.46-server.txt)
[latest.log](https://github.com/user-attachments/files/16473896/latest.log)

After disabling the sakura grove OTBWG biome. Same thing with several other biomes.

**Comment by JT122406** [comment]
are you using a modpack that has other worldgen mods?

**Comment by lanwoodall423** [comment]
A custom modset with Tectonic, WW Expanded Ecosphere, Regions Unexplored, Lithostitched. Also using C2ME and noisium

**Comment by lanwoodall423** [comment]
[crash-2024-08-02_17.10.08-server.txt](https://github.com/user-attachments/files/16475382/crash-2024-08-02_17.10.08-server.txt)

Same issue on new 1.0.4 beta

**Comment by KB-Q** [comment]
Same issue!

**Comment by OxyMauron** [comment]
1.0.5-Beta, Forge, and WW Expanded Ecosphere. Everything other than support plugins and EE were disabled. 

https://pastebin.com/1XYFrSTg

**Comment by JT122406** [comment]
EE is incompatible see #16 

> 1.0.5-Beta, Forge, and WW Expanded Ecosphere. Everything other than support plugins and EE were disabled.
> 
> https://pastebin.com/1XYFrSTg

**Comment by JT122406** [comment]
Closing this issue follow #16 For issues with expanded Ecosphere or use Corgi's new https://www.curseforge.com/minecraft/mc-mods/feature-recycler to get around this issue till I can fix all the incompatible things
