### ISSUE TITLE
skyrise_vale village crashes with mca reborn

### ISSUE THREAD

**Issue by modpackmaker999** [Potion-Studios/Oh-The-Biomes-Weve-Gone#64]
all the other bwg villages work but if you go to a skyrise_vale village it crashes with error code -1

it says

 The game crashed whilst exception ticking world
Error: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0

this is the crash report

r---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-08-05 16:08:42
Description: Exception ticking world

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at net.minecraft.world.level.storage.loot.predicates.BonusLevelTableCondition.test(BonusLevelTableCondition.java:45) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.predicates.BonusLevelTableCondition.test(BonusLevelTableCondition.java:20) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at java.util.function.Predicate.lambda$and$0(Predicate.java:69) ~[?:?] {re:mixin}
	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer.m_79639_(LootPoolEntryContainer.java:34) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer.m_6562_(LootPoolSingletonContainer.java:67) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.entries.ComposableEntryContainer.m_79413_(ComposableEntryContainer.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.entries.CompositeEntryBase.m_6562_(CompositeEntryBase.java:44) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootPool.m_79058_(LootPool.java:59) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.storage.loot.LootPool.m_79053_(LootPool.java:94) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.storage.loot.LootTable.m_79131_(LootTable.java:85) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:117) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_287195_(LootTable.java:112) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour.m_49635_(BlockBehaviour.java:258) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_287290_(BlockBehaviour.java:774) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.level.block.Block.m_49869_(Block.java:253) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBlock,pl:mixin:A}
	at net.minecraft.world.level.block.Block.m_49950_(Block.java:263) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBlock,pl:mixin:A}
	at net.minecraft.world.level.block.LeavesBlock.m_213898_(LeavesBlock.java:48) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,pl:accesstransformer:B}
	at net.potionstudios.biomeswevegone.world.level.block.plants.tree.leaves.BWGFruitLeavesBlock.m_213898_(BWGFruitLeavesBlock.java:28) ~[Oh-The-Biomes-Weve-Gone-Forge-1.0.5-Beta.jar%23169!/:?] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222972_(BlockBehaviour.java:762) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.level.ServerLevel.m_8714_(ServerLevel.java:481) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:corgilib-common.mixins.json:MixinServerLevel,pl:mixin:APP:forge-mca.mixin.json:MixinServerWorld,pl:mixin:APP:ohthetreesyoullgrow.mixins.json:MixinServerLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:362) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:312) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:305) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:corgilib-common.mixins.json:MixinServerLevel,pl:mixin:APP:forge-mca.mixin.json:MixinServerWorld,pl:mixin:APP:ohthetreesyoullgrow.mixins.json:MixinServerLevel,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mod: 
	Oh The Biomes We've Gone (biomeswevegone), Version: 1.0.5-Beta
		Issue tracker URL: https://github.com/Potion-Studios/Potion-Studios-Oh-The-Biomes-Weve-Gone/issues
		at TRANSFORMER/biomeswevegone@1.0.5-Beta/net.potionstudios.biomeswevegone.world.level.block.plants.tree.leaves.BWGFruitLeavesBlock.m_213898_(BWGFruitLeavesBlock.java:28)
Stacktrace:
	at net.minecraft.world.level.storage.loot.predicates.BonusLevelTableCondition.test(BonusLevelTableCondition.java:45) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.predicates.BonusLevelTableCondition.test(BonusLevelTableCondition.java:20) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at java.util.function.Predicate.lambda$and$0(Predicate.java:69) ~[?:?] {re:mixin}
	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer.m_79639_(LootPoolEntryContainer.java:34) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer.m_6562_(LootPoolSingletonContainer.java:67) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.entries.ComposableEntryContainer.m_79413_(ComposableEntryContainer.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.entries.CompositeEntryBase.m_6562_(CompositeEntryBase.java:44) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootPool.m_79058_(LootPool.java:59) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.storage.loot.LootPool.m_79053_(LootPool.java:94) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.storage.loot.LootTable.m_79131_(LootTable.java:85) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:117) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_287195_(LootTable.java:112) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour.m_49635_(BlockBehaviour.java:258) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_287290_(BlockBehaviour.java:774) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.level.block.Block.m_49869_(Block.java:253) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBlock,pl:mixin:A}
	at net.minecraft.world.level.block.Block.m_49950_(Block.java:263) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBlock,pl:mixin:A}
	at net.minecraft.world.level.block.LeavesBlock.m_213898_(LeavesBlock.java:48) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,pl:accesstransformer:B}
	at net.potionstudios.biomeswevegone.world.level.block.plants.tree.leaves.BWGFruitLeavesBlock.m_213898_(BWGFruitLeavesBlock.java:28) ~[Oh-The-Biomes-Weve-Gone-Forge-1.0.5-Beta.jar%23169!/:?] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222972_(BlockBehaviour.java:762) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.level.ServerLevel.m_8714_(ServerLevel.java:481) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:corgilib-common.mixins.json:MixinServerLevel,pl:mixin:APP:forge-mca.mixin.json:MixinServerWorld,pl:mixin:APP:ohthetreesyoullgrow.mixins.json:MixinServerLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:362) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:312) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:305) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:corgilib-common.mixins.json:MixinServerLevel,pl:mixin:APP:forge-mca.mixin.json:MixinServerWorld,pl:mixin:APP:ohthetreesyoullgrow.mixins.json:MixinServerLevel,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['colingamer27'/546, l='ServerLevel[New World]', x=-3665.13, y=71.00, z=-846.81]]
	Chunk stats: 3259
	Level dimension: minecraft:overworld
	Level spawn location: World: (-352,72,-544), Section: (at 0,8,0 in -22,4,-34; chunk contains blocks -352,-64,-544 to -337,319,-529), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,-64,-1024 to -1,319,-513)
	Level time: 6659 game time, 6659 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 101624 (now: false), thunder time: 20428 (now: false)
	Known server brands: forge
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 891423232 bytes (850 MiB) / 3531603968 bytes (3368 MiB) up to 6643777536 bytes (6336 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: Rocket Lake
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Radeon RX 570 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=31.0.21912.14
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 22501.94
	Virtual memory used (MB): 16825.70
	Swap memory total (MB): 14440.63
	Swap memory used (MB): 1258.42
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6336m -Xms256m
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['colingamer27'/546, l='ServerLevel[New World]', x=-3665.13, y=71.00, z=-846.81]]
	Data Packs: vanilla, mod:corgilib, mod:terrablender, mod:forge, mod:geckolib, mod:architectury (incompatible), mod:mca (incompatible), mod:ohthetreesyoullgrow, mod:tectonic (incompatible), mod:biomeswevegone, tectonic/tectonic
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: forge-47.3.5
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		corgilib-forge-1.20.1-4.0.2.0.jar                 |CorgiLib                      |corgilib                      |4.0.2.0             |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.20.1-3.0.1.7.jar             |TerraBlender                  |terrablender                  |3.0.1.7             |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.3.5-universal.jar                 |Forge                         |forge                         |47.3.5              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		geckolib-forge-1.20.1-4.4.7.jar                   |GeckoLib 4                    |geckolib                      |4.4.7               |DONE      |Manifest: NOSIGNATURE
		architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |DONE      |Manifest: NOSIGNATURE
		minecraft-comes-alive-7.5.18+1.20.1-universal.jar |Minecraft Comes Alive         |mca                           |7.5.18+1.20.1       |DONE      |Manifest: NOSIGNATURE
		Oh The Trees You'll Grow-forge-1.20.1-1.2.0.jar   |Oh The Trees You'll Grow      |ohthetreesyoullgrow           |1.2.0               |DONE      |Manifest: NOSIGNATURE
		tectonic-forge-1.19.3-2.3.5a.jar                  |Tectonic                      |tectonic                      |2.3.5a              |DONE      |Manifest: NOSIGNATURE
		Oh-The-Biomes-Weve-Gone-Forge-1.0.5-Beta.jar      |Oh The Biomes We've Gone      |biomeswevegone                |1.0.5-Beta          |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 6bd80592-3f10-4a74-b7a4-04d30d545411
	FML: 47.3
	Forge: net.minecraftforge:47.3.5

**Comment by JT122406** [comment]
This is a leaf crash error see #56
